version: '3'
 
services:
  db:
    image: sneezymud/sneezymud-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_USER: sneezy
      MYSQL_PASSWORD: password
    container_name: sneezydb
    volumes:
      - sneezydb:/var/lib/mysql
    restart: always

  sneezy:
    depends_on:
      - db
    image: sneezymud/sneezymud:latest
    container_name: sneezy
    cap_add:
      - SYS_PTRACE
    ports:
        - "7900:7900"
    restart: always

  web:
    container_name: sneezy-web
    image: sneezymud/sneezymud-buildertools:latest
    ports:
        - "5001:5000"
    depends_on:
        - db
    restart: always
volumes:
  sneezydb:
