version: '3'
 
services:
  sneezy-db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: "111111"
      MYSQL_USER: sneezy
      MYSQL_PASSWORD: password
    container_name: sneezy-db
    volumes:
      - sneezydb:/var/lib/mysql
    restart: always

  sneezy:
    depends_on:
      - sneezy-db
        # image: sneezymud/sneezymud:15
    image: sneezy-dev
    command:
      - ./sneezy
    container_name: sneezy
    cap_add:
      - SYS_PTRACE
    ports:
        - "7900:7900"
    restart: always
    volumes:
      - sneezy-lib:/home/sneezy/lib/
      - .:/sneezymud-docker/

        #  web:
        #    container_name: sneezy-web
        #    image: sneezymud/sneezymud-buildertools:latest
        #    ports:
        #        - "5001:5000"
        #    depends_on:
        #        - sneezy-db
        #    restart: always
volumes:
  sneezydb:
  sneezy-lib:
