# TODO:
# container/with builder tools
# container/pod with websockify
# populate lib and db from backup using an init container

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sneezydb-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sneezy-files-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: db
        image: crsneezy.azurecr.io/sneezymud-db:1
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-persistence-files
      volumes:
      - name: db-persistence-files
        persistentVolumeClaim:
          claimName: sneezydb-disk

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    app: db

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sneezymud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sneezymud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sneezymud
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      initContainers:
      - name: wait-for-db
        image: mariadb:10.5
        command: ['sh', '-c', "until mysql -h db -u root --password=111111  < /dev/null ; do echo waiting for db; sleep 2; done"]
      # - name: populate-data
      #   image: ubuntu:focal
      #   command: ['sh', '-c', "while sleep 2; do echo waiting; done"]
      #   volumeMounts:
      #     - mountPath: /home/sneezy/lib
      #       name: sneezy-files-disk
      containers:
      - name: sneezymud
        image: crsneezy.azurecr.io/sneezymud:1
        ports:
        - containerPort: 7900
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        volumeMounts:
          - mountPath: /home/sneezy/lib
            name: sneezy-files-disk
      volumes:
      - name: sneezy-files-disk
        persistentVolumeClaim:
          claimName: sneezy-files-disk
---
apiVersion: v1
kind: Service
metadata:
  name: sneezymud
spec:
  type: LoadBalancer
  ports:
  - port: 7900
  selector:
    app: sneezymud