# TODO:
# container/with builder tools
# container/pod with websockify
# cronjob for refreshing certs

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sneezy-db-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sneezy-files-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sneezy-backups-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi

        # ---
        # apiVersion: v1
        # kind: PersistentVolumeClaim
        # metadata:
        #   name: sneezy-webclient-certs
        # spec:
        #   accessModes:
        #   - ReadWriteOnce
        #   storageClassName: default
        #   resources:
        #     requests:
        #       storage: 10Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sneezy-db
spec:
  serviceName: sneezy-db
  replicas: 1
  selector:
    matchLabels:
      app: sneezy-db
  template:
    metadata:
      labels:
        app: sneezy-db
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sneezy-db
        image: mariadb:10.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "111111"
        - name: MYSQL_USER
          value: "sneezy"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
          name: sneezy-db
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: sneezy-db-disk
      volumes:
      - name: sneezy-db-disk
        persistentVolumeClaim:
          claimName: sneezy-db-disk

---
apiVersion: v1
kind: Service
metadata:
  name: sneezy-db
  labels:
    app: sneezy-db
spec:
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: sneezy-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sneezymud
spec:
  serviceName: sneezy
  replicas: 1
  selector:
    matchLabels:
      app: sneezymud
  template:
    metadata:
      labels:
        app: sneezymud
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      initContainers:
      - name: wait-for-db
        image: mariadb:10.5
        command: ['sh', '-c', "until mysql -h sneezy-db -u root --password=111111  < /dev/null ; do echo waiting for db; sleep 2; done"]
      - name: populate-data-and-db
        image: mariadb:10.5
        command:
          - 'sh'
          - '-c'
          - |
            set -ex
            [ -f /home/sneezy/lib/tipsfile ] && exit 0
            apt-get update && apt-get install --yes --no-install-recommends ca-certificates curl
            echo "DROP USER IF EXISTS 'sneezy'@'%';" | mysql -h sneezy-db -u root --password=111111
            echo "FLUSH PRIVILEGES;" | mysql -h sneezy-db -u root --password=111111
            echo "CREATE DATABASE IF NOT EXISTS immortal CHARACTER SET utf8 COLLATE utf8_general_ci;" | mysql -h sneezy-db -u root --password=111111
            echo "CREATE DATABASE IF NOT EXISTS sneezy CHARACTER SET utf8 COLLATE utf8_general_ci;" | mysql -h sneezy-db -u root --password=111111
            echo "CREATE USER 'sneezy'@'%' IDENTIFIED BY 'password';" | mysql -h sneezy-db -u root --password=111111
            echo "GRANT ALL PRIVILEGES ON immortal.* to 'sneezy'@'%';" | mysql -h sneezy-db -u root --password=111111
            echo "GRANT ALL PRIVILEGES ON sneezy.* to 'sneezy'@'%';" | mysql -h sneezy-db -u root --password=111111
            cd /home/sneezy
            curl -L https://sneezymud.org/sneezybackups/latest.tar.xz | tar xvJ
            # Sneezy runs as UID=1000
            chown -R 1000:1000 lib
            mysql -h sneezy-db -u root --password=111111 < dbdump.sql
            rm dbdump.sql
        volumeMounts:
          - mountPath: /home/sneezy/lib
            name: sneezy-files-disk
              #       - name: generate-cert
              #         image: certbot/certbot
              #         args:
              #           - "certonly"
              #           - "--standalone"
              #           - "--agree-tos"
              #           - "-m"
              #           - "elmo.todurov@eesti.ee"
              #           - "-n"
              #           - "-d"
              #           - "sneezymud.org,www.sneezymud.org"
              #         ports:
              #         - containerPort: 80
              #           name: acme-http
              # volumeMounts:
              #   - mountPath: /etc/letsencrypt
              #     name: sneezy-webclient-certs
      containers:
      - name: sneezymud
        image: sneezymud/sneezymud:5
        ports:
        - containerPort: 7900
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        volumeMounts:
          - mountPath: /home/sneezy/lib
            name: sneezy-files-disk
              #       - name: sneezy-webclient
              #         image: sneezymud/webclient:5
              #         ports:
              #         - containerPort: 80
              #           name: webclient-http
              #         - containerPort: 443
              #           name: webclient-https
              #         volumeMounts:
              #           - mountPath: /etc/letsencrypt
              #             name: sneezy-webclient-certs
              #       - name: sneezy-websockify
              #         image: efrecon/websockify
              #         command:
              #           - "7901"
              #           - "sneezymud:7900"
              #         ports:
              #         - containerPort: 7901
              #           name: websocket
      volumes:
      - name: sneezy-files-disk
        persistentVolumeClaim:
          claimName: sneezy-files-disk
            #       - name: sneezy-webclient-certs
            #         persistentVolumeClaim:
            #           claimName: sneezy-webclient-certs

---
apiVersion: v1
kind: Service
metadata:
  name: sneezymud
spec:
  type: LoadBalancer
  ports:
  - port: 7900
    name: sneezymud
#   - port: 80
#     name: acme-http
#   - port: 80
#     name: webclient-http
#   - port: 443
#     name: webclient-https
#   - port: 7901
#     name: websocket
  selector:
    app: sneezymud


      # ---
      # apiVersion: batch/v1beta1
      # kind: CronJob
      # metadata:
      #   name: sneezy-daily-backup
      # spec:
      #   schedule: "* * */1 * *"
      #   jobTemplate:
      #     spec:
      #       template:
      #         spec:
      #           restartPolicy: OnFailure
      #           volumes:
      #           - name: sneezy-files-disk
      #             persistentVolumeClaim:
      #               claimName: sneezy-files-disk
      #           - name: sneezy-backups-disk
      #             persistentVolumeClaim:
      #               claimName: sneezy-backups-disk
      #           containers:
      #           - name: sneezy-backup
      #             image: busybox
      #             volumeMounts:
      #               - mountPath: /home/sneezy/lib
      #                 name: sneezy-files-disk
      #                 readOnly: true
      #               - mountPath: /sneezybackups
      #                 name: sneezy-backups-disk
      #             args:
      #             - /bin/sh
      #             - -c
      #             - |
      #               set -ex
      # 
      #               # Important locations
      #               TEMPLOCATION="/tmp"
      #               SNEEZYLIB="/home/sneezy"
      #               BACKUPDIR="/sneezybackups"
      # 
      #               # Setting the backup filename
      #               if [ -z "$1" ]
      #               then
      #                       FNAME="$BACKUPDIR/sneezy-backup-`date +%s`.tar.xz"
      #               else
      #                       FNAME="$1"
      #               fi
      # 
      #               # Dump the database (this takes a bit of time)
      #               mysqldump -h sneezy-db -u root -p111111 --databases sneezy immortal > "$TEMPLOCATION/dbdump.sql"
      # 
      #               # Perform the backup
      #               tar -cJf "$FNAME" --exclude='core' -C "$TEMPLOCATION" dbdump.sql -C "$SNEEZYLIB" lib || true  # tends to fail with "file changed" or "file deleted" -- proper LVM snapshotting would be better
      # 
      #               # Remove our temps
      #               rm "$TEMPLOCATION/dbdump.sql"
      # 
      #               # Push the backup to any online repositories.
      #               #drive push -no-prompt -quiet -destination backups "$FNAME"