spec:
  template:
    spec:
      containers:
      - name: controller
        ports:
         - containerPort: 7900
           hostPort: 30991
         - containerPort: 7901
           hostPort: 30992
